version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  doping-tech-api:
    build: .
    container_name: doping-tech-api
    ports:
      - "8080:8080"
    links:
       - redis
    deploy:
      restart_policy:
        condition: on-failure

